# Configure the workspace

setwd("~/Documents/projects/Stanford projects/temperature and vector-borne disease/SDM learning project/Aedes_sierrensis_SDM_v3")

library(blockCV)
library(caret)
library(corrplot)
library(data.table)
library(dismo)
library(dplyr)
library(forcats)
library(future.apply)
library(ggnewscale)
library(ggplot2)
library(mltools)
library(mgcv)
library(patchwork)
library(pdp)
library(PerformanceAnalytics)
library(pROC) 
library(purrr)
library(raster)
library(rBayesianOptimization)
library(RColorBrewer)
library(rgbif)
library(rnaturalearth)
library(rsample)
library(sf)
library(SHAPforxgboost)
library(spatialsample)
library(terra)
library(tidyr)
library(tidytext)
library(tidyverse)
library(vip)
library(xgboost)


